#!/bin/zsh

rm -rf build
mkdir build
cmake -B build -S PTZMacInstaller
cmake --build build
cp build/PTZMacInstaller ptz-mac-installer/PTZMacInstaller.app/Contents/MacOS/
hdiutil create -srcfolder ptz-mac-installer -ov -format UDZO ptz-mac-installer.dmg

