name: Build ptz-obs-plugin for Windows

on:
  workflow_dispatch:
  
jobs:
  build-windows:    
    runs-on: windows-2022
    steps:   
    - name: Clone plugin repository
      run: git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/havsys/ptzoptics-obs
      shell: cmd  
    - name: Build installer
      run: ptzoptics-obs\gh_actions\windows.cmd ${{ secrets.GH_ACCESS_TOKEN }}
      shell: cmd      
    - uses: actions/upload-artifact@v3
      with:
        name: PtzObsPluginInstaller-win-x64
        path: ptzoptics-obs\installers-src\win\x64\Release\PtzObsPluginInstaller.exe
