name: Build ptz-obs-plugin for macOS Intel

on:
  workflow_dispatch:
  
jobs:
  build-macos-intel:    
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Build installer
      env:
        CODESIGN_CERTIFICATE_BASE64: ${{ secrets.APP_CERT_MACOS }}
        CODESIGN_P12_PASSWORD: ${{ secrets.APP_CERT_MACOS_PWD }}        
        SIGN_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.INSTALL_CERT_MACOS }}
        SIGN_INSTALLER_P12_PASSWORD: ${{ secrets.INSTALL_CERT_MACOS_PWD }}        
        TEMP_KEYCHAIN_PASSWORD: havsys
      run: gh_actions/macos.sh
    - name: "Notarize Release Build"
      uses: BoundfoxStudios/action-xcode-notarize@v1
      with:
        product-path: "PtzOpticsOBSPlugin_x86_64.pkg"
        appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
        appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
    - name: "Staple Release Build"
      uses: BoundfoxStudios/action-xcode-staple@v1
      with:
        product-path: "PtzOpticsOBSPlugin_x86_64.pkg"
    - uses: actions/upload-artifact@v3
      with:
        name: PtzOpticsOBSPlugin_x86_64
        path: PtzOpticsOBSPlugin_x86_64.pkg
