name: Build ptz-obs-plugin for Windows

on:
  workflow_dispatch:
  
jobs:
  build-windows:    
    runs-on: windows-2022
    steps:   
    - uses: actions/checkout@v3
    - name: Build installer
      run: gh_actions\windows.cmd
      shell: cmd      
    - uses: actions/upload-artifact@v3
      with:
        name: PtzObsPluginInstaller-win-x64
        path: installers-src\win\x64\Release\PtzObsPluginInstaller.exe
