name: Test notarization

on:
  workflow_dispatch:
  
jobs:
  test-notarization:    
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Submit PKG for notarization
      run: xcrun notarytool submit gh_actions/PtzOpticsOBSPlugin_x86_64.pkg --wait --apple-id ${{ secrets.NOTARIZATION_USERNAME }} --password ${{ secrets.NOTARIZATION_PASSWORD }} --team-id 32VFWEFED4
    - name: Staple PKG
      run: xcrun stapler staple gh_actions/PtzOpticsOBSPlugin_x86_64.pkg
        

